### ISSUE TITLE
Some SSD IP core not found

### ISSUE THREAD

**Issue by xjxgyc** [Cosmos-OpenSSD/Cosmos-OpenSSD-plus#1]
I use OpenSSD2_bd.tcl  in prebuilt hdf file to create a zynq project. I got some error. Because  some related SSD ip core did not find, but OpenSSD website that related to some openSSD file did not open.  Can you offer some ip core in the hardware project? Thank you !

**Comment by Cosmos-OpenSSD** [comment]
You can find hardware ip cores at Cosmos-plus-OpenSSD/tree/master/Source/IPRepo.
