### ISSUE TITLE
New 2CH8WAY-1.0.2Project can't run successfully due to firmware

### ISSUE THREAD

**Issue by shengwenliang** [Cosmos-OpenSSD/Cosmos-OpenSSD-plus#10]
Hi, 
i find your update new project 2ch8way-1.0.2 which fixed ecc bug, and i also run this project via vivado2014.4 , the project run successfully in vivado and export hardware to SDK ,but when i run firmware GreedyFTL-2.7.1.c , it fail ,and end in  **_"block erasure start"_** in function void InitBlockMap(unsigned int badBlockTableAddr) of page_map.c 
after my test, i find the firmware can not  run at 
PushToSubReqQueue(j % CHANNEL_NUM, j / CHANNEL_NUM, V2FCommand_BlockErase, i*PAGE_NUM_PER_BLOCK, NONE, NONE); (belong to page map)
so could you tell me how to solve it?
Thanks

**Comment by dvoytik** [comment]
Hi all,

I also see the same problem on commit `71fdc54 2017-09-11 openssd Add predefined project 1.0.2 (ECC hang bug fixed)`.

```
Thread [1] (Suspended: Signal 'SIGINT' received. Description: Interrupt.)	
	6 ExeLowLevelReq() low_level_scheduler.c:1508 0x0010ecf4	    <--- spins here
	5 PushToSubReqQueue() low_level_scheduler.c:351 0x00106254	
	4 InitBlockMap() page_map.c:114 0x00112224	
	3 InitFtlMapTable() init_ftl.c:103 0x00103da8	
	2 nvme_main() nvme_main.c:98 0x00103480	
	1 main() main.c:129 0x00112068	

```

```c
void PushToSubReqQueue(int chNo, int wayNo, unsigned int request, unsigned int rowAddress, unsigned int pageDataBuf, unsigned int spareDataBuf)
{
	int rear;
	unsigned int phyRowAddr;

	while(((srqPointer->rqPointerEntry[chNo][wayNo].rear + 1) % SUB_REQ_QUEUE_DEPTH) == srqPointer->rqPointerEntry[chNo][wayNo].front)
		ExeLowLevelReq(REQ_QUEUE);
 ...
}
```

The firmware infinitely spins in these two lines.

**Comment by dvoytik** [comment]
CC @Sangjin-Lee

**Comment by Cosmos-OpenSSD** [comment]
We found that some of source files in predefined 1.0.2 project are incorrectly generated. We are preparing for a fix.
