### ISSUE TITLE
page read failure due to ECC module bug

### ISSUE THREAD

**Issue by Cosmos-OpenSSD** [Cosmos-OpenSSD/Cosmos-OpenSSD-plus#2]
ECC-related modules in Tiger4NSC and BCHSharedKESforTiger4 of IPRepo 1.0.0 and predefined project 2Ch-8Way 1.0.0 have a bug, and the ECC module always reports page read failure (ECC fail) on read operation. We are aware of this issue and preparing source code patches.

**Comment by dvoytik** [comment]
Hi @Sangjin-Lee, did you fix this issue?

**Comment by Sangjin-Lee** [comment]
As I know, yes. Use [this](https://github.com/Cosmos-OpenSSD/Cosmos-plus-OpenSSD/tree/master/source/hardware/nfc-substrate/bch_shared_kes-1.0.1)

**Comment by Cosmos-OpenSSD** [comment]
This issue has been fixed (predefined 1.0.3)
