### ISSUE TITLE
undefine XPAR_FABRIC_NVMEHOSTCONTROLLER_0_DEV_IRQ_ASSERT_INTR

### ISSUE THREAD

**Issue by mydonh** [Cosmos-OpenSSD/Cosmos-OpenSSD-plus#8]
Cannot find the value of XPAR_FABRIC_NVMEHOSTCONTROLLER_0_DEV_IRQ_ASSERT_INTR in any releases.

Thanks

**Comment by Cosmos-OpenSSD** [comment]
include  "xparameters.h" header file (from your_project_name_bsp\ps7_cortexa9_0\include) in your source file.

Line 299:
/***Definitions for Core_nIRQ/nFIQ interrupts ****/
/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_NVMEHOSTCONTROLLER_0_DEV_IRQ_ASSERT_INTR 61

**Comment by mydonh** [comment]
Thanks for your replied.
My xparameters.h does not has that fabric interrupt definition.

Do you might to attach your BD files?
Thanks again

**Comment by Cosmos-OpenSSD** [comment]
if the definition does not present in your xparameters.h file, it means that something went wrong.
BTW, I do not understand what you want. I think BD files are not relevan to xparameters.h file...

**Comment by mydonh** [comment]
Please attach your xparameter.h
I attached my BD and NVMe Host Controllers setup. I did not see where is the Fabric Interrupt connected to ps7_scugic_0

Anyway, very appreciate for your reply.
![nvme_prob3](https://user-images.githubusercontent.com/23559776/28658888-3020e0a2-7262-11e7-8bae-27283c7a78b1.png)
![nvme_prob2](https://user-images.githubusercontent.com/23559776/28658889-3022c192-7262-11e7-9a17-c4f07addce34.png)
![nvme_prob1](https://user-images.githubusercontent.com/23559776/28658890-3022bc4c-7262-11e7-9929-86202f85b51a.png)
